### ISSUE TITLE
Push the builds on artifactory

### ISSUE THREAD

**Issue by arnobl** [inspectorguidget/inspectorguidget-data#1]
http://maven.inria.fr/artifactory/webapp/

**Comment by arnobl** [comment]
May have to create crendantials in Jenkins:
https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials

An example that seems relevant:
https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/maven-example/Jenkinsfile

**Comment by ElRichu** [comment]
https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins

**Comment by arnobl** [comment]
Done
